### ISSUE TITLE
Error messages during processing

### ISSUE THREAD

**Issue by serbinsh** [amcmahonBNL/UnispecProcessing#13]
```
130-199-9-232:UniSpec_Processing sserbin$ python3.5 Main.py
Found 4 runs in /Users/sserbin/Data/Projects/NGEE-Arctic/Tram_Spectra/20150709/.
    WPs Stops

0:  -1  55
1:  2   136
2:  2   136
3:  2   136
4:  2   20
Saturated Measurement Count
        Ch_B    Ch_A

0 WPs and 0 stops saturated.
Traceback (most recent call last):
  File "Main.py", line 82, in <module>
    main()
  File "Main.py", line 65, in main
    avg_WP = Spec.AvgWPs(intdata_WPs)
  File "/Users/sserbin/Data/Projects/NGEE-Arctic/UniSpec_Processing/BasicProcessing.py", line 321, in AvgWPs
    newdata = np.array(np.zeros_like(data[0]))
IndexError: index 0 is out of bounds for axis 0 with size 0

```

```

130-199-9-232:UniSpec_Processing sserbin$ python3.5 Main.py
Found 6 runs in /Users/sserbin/Data/Projects/NGEE-Arctic/Tram_Spectra/20150518/.
    WPs Stops

0:  -1  19
1:  2   136
2:  2   136
3:  2   136
4:  2   136
5:  2   136
6:  2   80
Saturated Measurement Count
        Ch_B    Ch_A
Stop 0:     0   56
Stop 1:     0   60
Stop 2:     0   32
Stop 3:     0   32
Stop 4:     0   16
Stop 5:     0   6
Stop 6:     0   10
Stop 7:     0   36
Stop 8:     0   41
Stop 9:     0   54
Stop 10:        0   50
Stop 11:        0   64
Stop 12:        0   56
Stop 13:        0   33
Stop 14:        0   57
Stop 15:        0   61
Stop 16:        0   61
Stop 17:        0   50
Stop 18:        0   37

0 WPs and 19 stops saturated.
Traceback (most recent call last):
  File "Main.py", line 82, in <module>
    main()
  File "Main.py", line 65, in main
    avg_WP = Spec.AvgWPs(intdata_WPs)
  File "/Users/sserbin/Data/Projects/NGEE-Arctic/UniSpec_Processing/BasicProcessing.py", line 321, in AvgWPs
    newdata = np.array(np.zeros_like(data[0]))
IndexError: index 0 is out of bounds for axis 0 with size 0

```

What am I doing wrong?

**Comment by serbinsh** [comment]
Ahhh.  For some reason some of the runs have a small set of data at the beginning that doesn't correspond to a white plate. If I delete these then they process fine.  What is causing the strange set of data at the start of the day? Leftovers from the previous days late night run?
