### ISSUE TITLE
Error during processing with *_end.spu suffix

### ISSUE THREAD

**Issue by serbinsh** [amcmahonBNL/UnispecProcessing#15]
@amcmahon01 

I am getting this error:

```
130-199-9-232:UniSpec_Processing sserbin$ vi src/config.txt
130-199-9-232:UniSpec_Processing sserbin$ python3.6 src/Main.py
Traceback (most recent call last):
  File "src/Main.py", line 88, in <module>
    main()
  File "src/Main.py", line 28, in main
    run_count, WP_count, stop_count = spec.getFileLists()
  File "/Users/sserbin/Data/GitHub/UniSpec_Processing/src/BasicProcessing.py", line 116, in getFileLists
    if int(file[-7:-4:]) < int(lastfile[-7:-4:]):
ValueError: invalid literal for int() with base 10: 'end'
```

Recall in 2016 we added a white plate to the end of the run, and those are designated with the _end.spu

Before that we didn't have a white plate at the end.  I just want to be sure that prior to an end WP we aren't using the last measurement as another white plate correct? That is, we only average the last measurement if it has the *_end.spu suffix?

**Comment by amcmahon01** [comment]
The code right now identifies white plate files by the "whiteplate identifier" suffix in the config file, by default "000".  So it doesn't recognize the *_end.spu files as anything, causing the error.  I can change it to search for multiple identifier strings so that we can use both "000" and "end", but in the meantime, it's been ignoring the end files, so that's why it looks like one white plate is missing when it gives you stats.

**Comment by serbinsh** [comment]
@amcmahon01 Thanks!

Not a massive priority right now. Also, it may be good to average the first three together then average the first average and the last plate so that they have equal weight, make sense?

**Comment by serbinsh** [comment]
@amcmahon01 any chance we could update this code such that it can handle the "end" files as well as 000 in the processing?  I would like to try and get this data processing wrapped up before the field season.

Thanks!

**Comment by amcmahon01** [comment]
@serbinsh Yes, this shouldn't be a problem.  Just to clarify your comment above, we want to average the three white plate measurements at the beginning to create a "starting" reference and then average this with the "ending" reference for which there is only one measurement, correct?  Also would we be better off interpolating between them or do you think that's more trouble than it's worth?
