### ISSUE TITLE
Task: Combine the 2018 and 2020 features/improvements/fixes into a new working branch for testing

### ISSUE THREAD

**Issue by serbinsh** [amcmahonBNL/UnispecProcessing#20]
@amcmahon01 I am uncovering and remembering where we were now on this. 

1) 2018 branch has the new features to have start and end whiteplates and selection of different methods for how to use these.  You also added new flags to the config, which i was able to figure out in the BasicProcessing.py

2) But, when i tried running this branch, I had to change some "else if" to "elif" and "is not" to "!=" to avoid some errors, eg 

```
(py39) Wolfmans-MacPro-Desktop:UniSpec_Processing_2018 sserbin$ python src/BasicProcessing/Main.py
/Users/sserbin/Data/GitHub/UniSpec_Processing_2018/src/BasicProcessing/BasicProcessing.py:121: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if lastfile is not "":
Traceback (most recent call last):
  File "/Users/sserbin/Data/GitHub/UniSpec_Processing_2018/src/BasicProcessing/Main.py", line 6, in <module>
    from BasicProcessing import UnispecProcessing
  File "/Users/sserbin/Data/GitHub/UniSpec_Processing_2018/src/BasicProcessing/BasicProcessing.py", line 53, in <module>
    class UnispecProcessing:
  File "/Users/sserbin/Data/GitHub/UniSpec_Processing_2018/src/BasicProcessing/BasicProcessing.py", line 65, in UnispecProcessing
    WP_end[[]]
    ```

3) but even after that I am hitting this error??

```
(py39) Wolfmans-MacPro-Desktop:UniSpec_Processing_2018 sserbin$ python src/BasicProcessing/Main.py
Found 3 runs in /Users/sserbin/Data/GitHub/UniSpec_Processing_2018/example_data/20150725/.
	WPs	Stops

0:	3	137
1:	3	137
2:	3	137
3:	3	137
Saturated Measurement Count
		Ch_B	Ch_A

0 WPs and 0 stops saturated.
Traceback (most recent call last):
  File "/Users/sserbin/Data/GitHub/UniSpec_Processing_2018/src/BasicProcessing/Main.py", line 91, in <module>
    main()
  File "/Users/sserbin/Data/GitHub/UniSpec_Processing_2018/src/BasicProcessing/Main.py", line 74, in main
    WP_array = create_WP_array(avg_WP_start,WP_end_data,Stop_data)
NameError: name 'create_WP_array' is not defined
```

4) finally, there is an issue, #19 that shows how to fix the reflectance calculation bug that isnt provided in a real "2020" branch as you mention??  So in effect I dont actually have access to any of the working fixes in 2018 or the corrected reflectance calculation in your 2020 branch?  This is why I ask that you keep your changes pushed up to keep track

So it seems, as I state, we need to bring together a working version of the 2018 branch with the 2020 fixes so that I can then try running that on test data.  Are you able to pull these two together and then push a new branch or update for me?

I think I know how to config the config file to run the two whiteplate code, I just seem to have remaining bugs that arent allowing me to test.  Also I assume for those years where we DONT have both 000 and *.end whiteplates, we can just put 000 in both? 

For example

```
[Input]
SourcePath = /Users/sserbin/Data/GitHub/UniSpec_Processing_2018/example_data/20150725/
WP_Identifier = 000
WP_end_Identifier = 000
WP_avg_mode=interpolate
HeaderLines = 11
```

Is this all making sense and helping remind where we are? This 2020 change is what I recall you mentioning at some point more recently but again I do not see a new branch here in the repo

**Comment by serbinsh** [comment]
Update. I realized what was the one error above I had to change 

```
create_WP_array(avg_WP_start,WP_end_data,Stop_data)
```

to

```
spec.create_WP_array(avg_WP_start,WP_end_data,Stop_data)
```

But given finding these issues, I wonder if even the 2018 branch isnt updated to the lastest version of that which you had?  It seems there are too many bugs and I assume maybe that isnt up to date?

also after doing that I now get

```
(py39) Wolfmans-MacPro-Desktop:UniSpec_Processing_2018 sserbin$ python src/BasicProcessing/Main.py
Found 3 runs in /Users/sserbin/Data/GitHub/UniSpec_Processing_2018/example_data/20150725/.
	WPs	Stops

0:	3	137
1:	3	137
2:	3	137
3:	3	137
Saturated Measurement Count
		Ch_B	Ch_A

0 WPs and 0 stops saturated.
<__array_function__ internals>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
Traceback (most recent call last):
  File "/Users/sserbin/Data/GitHub/UniSpec_Processing_2018/src/BasicProcessing/Main.py", line 91, in <module>
    main()
  File "/Users/sserbin/Data/GitHub/UniSpec_Processing_2018/src/BasicProcessing/Main.py", line 79, in main
    R = spec.refl(intdata_Stops, WP_array)
  File "/Users/sserbin/Data/GitHub/UniSpec_Processing_2018/src/BasicProcessing/BasicProcessing.py", line 439, in refl
    refl[s_idx, 1] = (stop[consts.int_CH_B] / WP_data[s_idx][consts.int_CH_A]) * (stop[consts.int_CH_A] / stop[consts.int_CH_B])
IndexError: index 2 is out of bounds for axis 0 with size 2
```
