### ISSUE TITLE
Error attempting to run Main.py on mac osx

### ISSUE THREAD

**Issue by serbinsh** [amcmahonBNL/UnispecProcessing#4]
@amcmahonBNL 
I am still having trouble running the Main.py code to process some data on my computer.  Here is the error output:

```
130-199-9-232:UniSpec_Processing sserbin$ python Main.py
Traceback (most recent call last):
  File "Main.py", line 80, in <module>
    main()
  File "Main.py", line 23, in main
    Spec = UnispecProcessing(path + r'\config.txt')
  File "/Users/sserbin/Data/Projects/NGEE-Arctic/UniSpec_Processing/BasicProcessing.py", line 80, in __init__
    InputParams = config['Input']
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/configparser.py", line 995, in __getitem__
    raise KeyError(key)
KeyError: 'Input'
```

Any ideas?  Maybe we can sit together and make sure I am running things properly, as well as properly setting up my environment.

**Comment by serbinsh** [comment]
Here is my config.txt

```
[Input]
SourcePath = /Users/sserbin/Data/Projects/NGEE-Arctic/Tram_Spectra/20150625
WP_Identifier = 000
HeaderLines = 10

[Output]
OutputPath = /Users/sserbin/Data/Projects/NGEE-Arctic/Tram_Spectra/20150625/out
OutputPrefix = NGEE-Artcic_
```

**Comment by serbinsh** [comment]
When running Eclipse to debug code:

```
pydev debugger: starting (pid: 98607)
Traceback (most recent call last):
  File "/Users/sserbin/.p2/pool/plugins/org.python.pydev_4.4.0.201510052309/pysrc/pydevd.py", line 2364, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Users/sserbin/.p2/pool/plugins/org.python.pydev_4.4.0.201510052309/pysrc/pydevd.py", line 1784, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/sserbin/Data/Projects/NGEE-Arctic/UniSpec_Processing/Main.py", line 6, in <module>
    from BasicProcessing import UnispecProcessing
  File "/Users/sserbin/Data/Projects/NGEE-Arctic/UniSpec_Processing/BasicProcessing.py", line 8, in <module>
    import configparser
ImportError: No module named configparser

```

**Comment by serbinsh** [comment]
OK, so attempting to use python3.5 @amcmahonBNL.  To do that I have installed python3.5 and are running commands using python3.5 instead of default python. E.g. 

```
130-199-9-232:UniSpec_Processing sserbin$ python3.5 -m pip install numpy
Collecting numpy
  Downloading numpy-1.10.1-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.7MB)
    100% |████████████████████████████████| 3.7MB 155kB/s
Installing collected packages: numpy
Successfully installed numpy-1.10.1
```

**Comment by serbinsh** [comment]
OK, @amcmahonBNL here is what happened before I installed required packages with 3.5:

```
130-199-9-232:UniSpec_Processing sserbin$ python3.5 Main.py
Traceback (most recent call last):
  File "Main.py", line 6, in <module>
    from BasicProcessing import UnispecProcessing
  File "/Users/sserbin/Data/Projects/NGEE-Arctic/UniSpec_Processing/BasicProcessing.py", line 11, in <module>
    import numpy as np
ImportError: No module named 'numpy'
```

After I installed numpy, scipy, and matplotlib I still get the configparser error, but now with 3.5:

```
130-199-9-232:UniSpec_Processing sserbin$ python3.5 Main.py
Traceback (most recent call last):
  File "Main.py", line 80, in <module>
    main()
  File "Main.py", line 23, in main
    Spec = UnispecProcessing(path + r'\config.txt')
  File "/Users/sserbin/Data/Projects/NGEE-Arctic/UniSpec_Processing/BasicProcessing.py", line 80, in __init__
    InputParams = config['Input']
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/configparser.py", line 957, in __getitem__
    raise KeyError(key)
KeyError: 'Input'

```

**Comment by serbinsh** [comment]
Strange, I can load configparser in python just fine so I don't think finding the module is the issue?

**Comment by amcmahon01** [comment]
I just noticed in this line:

File "Main.py", line 23, in main
Spec = UnispecProcessing(path + r'\config.txt')

...it's appending a backslash before config.txt. Does that need to be changed to a forward slash for macs? Maybe it's not finding the file and that's why it can't find the 'Input' key?

-----Original Message-----

**Comment by serbinsh** [comment]
I will try that!!

FYI - This is also pretty helpful
https://docs.python.org/2/library/pdb.html

e.g. python3.5 -m pdb Main.py

**Comment by serbinsh** [comment]
A bit of stepping through

```
>>> import os.path
>>> path = str(os.path.realpath('.'))
>>> path
'/Users/sserbin/Data/Projects/NGEE-Arctic/UniSpec_Processing'

>>> path + r'config.txt'
'/Users/sserbin/Data/Projects/NGEE-Arctic/UniSpec_Processingconfig.txt'
```

SO, needs a forward slash to get:

'/Users/sserbin/Data/Projects/NGEE-Arctic/UniSpec_Processing/config.txt'

AND

After changing to:
Spec = UnispecProcessing(path + r'/config.txt')

I get a new error further in the code @amcmahonBNL! (Progress)

```
130-199-9-232:UniSpec_Processing sserbin$ python3.5 Main.py
Found 3 runs in /Users/sserbin/Data/Projects/NGEE-Arctic/Tram_Spectra/20150625.
    WPs Stops

0:  2   136
1:  2   136
2:  2   136
3:  2   93
Traceback (most recent call last):
  File "Main.py", line 80, in <module>
    main()
  File "Main.py", line 39, in main
    WP_data = Spec.ReadFiles(Spec.WPs[run], Spec.HeaderLines)
  File "/Users/sserbin/Data/Projects/NGEE-Arctic/UniSpec_Processing/BasicProcessing.py", line 142, in ReadFiles
    sf = open(self.SourcePath + "\\" + flist[i], "Ur")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sserbin/Data/Projects/NGEE-Arctic/Tram_Spectra/20150625\\Uni_2015-06-25__00_02_26_000.spu'
```

Suggesting we need to work on path issues in the code for easier cross-platform use

**Comment by serbinsh** [comment]
Trying to get farther by editing line 142 of BasicProcessing.py

from 

```
sf = open(self.SourcePath + "\\" + flist[i], "Ur")
```

TO

```
sf = open(self.SourcePath + "//" + flist[i], "Ur")
```

**Comment by serbinsh** [comment]
OK, that last edit worked @amcmahonBNL . Code now runs:

```
Found 3 runs in /Users/sserbin/Data/Projects/NGEE-Arctic/Tram_Spectra/20150625.
    WPs Stops

0:  2   136
1:  2   136
2:  2   136
3:  2   93
Saturated Measurement Count
        Ch_B    Ch_A

0 WPs and 0 stops saturated.
Writing file: NGEE-Artcic_2015-06-25__00_02_26.csv
Wrote 136 row(s).
File closed.
Saturated Measurement Count
        Ch_B    Ch_A

0 WPs and 0 stops saturated.
Writing file: NGEE-Artcic_2015-06-25__15_00_21.csv
Wrote 136 row(s).
File closed.
Saturated Measurement Count
        Ch_B    Ch_A

0 WPs and 0 stops saturated.
Writing file: NGEE-Artcic_2015-06-25__19_54_36.csv
Wrote 136 row(s).
File closed.
Saturated Measurement Count
        Ch_B    Ch_A

0 WPs and 0 stops saturated.
Writing file: NGEE-Artcic_2015-06-25__22_51_15.csv
Wrote 93 row(s).
File closed.
```

**Comment by amcmahon01** [comment]
@serbinsh Just tested the updated code on Windows and it's working well.

**Comment by serbinsh** [comment]
I am closing this issue since it has now been addressed.
